/**
 * Compact, deterministic documentation for coding agents.
 *
 * A Pilot already knows its capability, targets, fields and credentials. An
 * agent should not spend a model turn opening manifests and SDK internals to
 * reconstruct that information, so this renders the installed state into one
 * small file. No model is involved and no credential values are included.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { JOBS_CAPABILITY } from "../capability/jobs.js";
import { CapabilityRegistry } from "../capability/registry.js";
import { PilotStore } from "../pilots/store.js";
import type { PilotEnv } from "../shared/env.js";
import type { FieldSpec } from "../shared/schema.js";
import { flagString, type ParsedArgs } from "./args.js";

export const DEFAULT_DOCS_FILE = "PILOT.md";

function fieldLine(field: FieldSpec): string {
  const optional = field.required ? "required" : "optional";
  return `- \`${field.name}\`: ${field.type}, ${optional} — ${field.description}`;
}

const JOB_RESULT_LINES = [
  "- `title`: string, required — normalized job title",
  "- `company`: string, required — normalized company name",
  "- `location`: string | null — normalized work location",
  "- `type`: internship | full-time | part-time | contract | temporary | unknown",
  "- `url`: string, required — absolute posting URL",
  "- `postedAt`: string | null — posting date when available",
  "- `source`: string — Pilot id that returned the job",
  "- `attributes`: object — validated capability-extension fields",
];

function example(capability: string): string {
  if (capability === JOBS_CAPABILITY) {
    return `import { pilot } from "@pilot/sdk";

const { jobs, sources } = await pilot()
  .capability("jobs.search")
  .search({ keywords: "software engineer", type: "internship", limit: 10 });`;
  }
  const short = capability.split("@")[0]!;
  return `import { pilot } from "@pilot/sdk";

const { records, sources } = await pilot()
  .capability("${short}")
  .search({ params: {}, limit: 10 });`;
}

export function renderPilotDocs(env: PilotEnv): string {
  const store = new PilotStore(env);
  const installed = store.all();
  const registry = new CapabilityRegistry(env);
  const capabilities = [...new Set(installed.map((item) => item.pilot.capability).filter(Boolean))] as string[];
  const lines = [
    "# Pilot API",
    "",
    "Generated by `pilot docs`. This is the concise integration contract; do not inspect",
    "Pilot's `node_modules` implementation unless a documented call fails.",
    "",
    "Running an installed Pilot makes no compiler-model call.",
  ];

  if (installed.length === 0) {
    lines.push("", "No Pilots are installed. Run `pilot create <url>` or `pilot install <id>`." );
    return `${lines.join("\n")}\n`;
  }

  for (const capability of capabilities.sort()) {
    const targets = installed.filter((item) => item.pilot.capability === capability);
    const definition = registry.find(capability);
    const fields = definition?.schema.fields ?? targets[0]!.pilot.schema.fields;
    lines.push(
      "",
      `## ${capability}`,
      "",
      `Targets: ${targets.map((item) => `\`${item.pilot.id}\``).join(", ")}`,
      "",
      "```js",
      example(capability),
      "```",
      "",
      "Returns:",
      "",
      ...(capability === JOBS_CAPABILITY ? JOB_RESULT_LINES : fields.map(fieldLine)),
    );

    if (capability === JOBS_CAPABILITY) {
      lines.push(
        "",
        "The extraction schema's `employmentType` is normalized to the SDK result's `type`; application code should use `type`.",
      );
    }

    const credentials = [...new Set(targets.flatMap((item) => item.pilot.credentials ?? []).map((item) => item.env))];
    if (credentials.length > 0) {
      lines.push("", `Credentials required by some targets: ${credentials.map((name) => `\`${name}\``).join(", ")}`);
    }
  }

  const adHoc = installed.filter((item) => item.pilot.capability === null);
  if (adHoc.length > 0) {
    lines.push("", "## Ad-hoc Pilots", "");
    for (const item of adHoc) {
      lines.push(`- \`${item.pilot.id}\`: ${item.pilot.schema.fields.map((field) => field.name).join(", ")}`);
    }
  }

  return `${lines.join("\n")}\n`;
}

export function writePilotDocs(env: PilotEnv, output = DEFAULT_DOCS_FILE): string {
  const file = path.resolve(env.projectRoot, output);
  writeFileSync(file, renderPilotDocs(env));
  return file;
}

export function runDocs(env: PilotEnv, args: ParsedArgs): number {
  const body = renderPilotDocs(env);
  if (args.flags["dry-run"] === true) {
    process.stdout.write(body);
    return 0;
  }
  const file = writePilotDocs(env, flagString(args, "out") ?? DEFAULT_DOCS_FILE);
  process.stdout.write(`Wrote ${path.relative(env.projectRoot, file) || file}\n`);
  return 0;
}
