/**
 * Turn the installed capabilities into TypeScript.
 *
 * `pilot_capabilities` tells an agent what the fields are; this tells the
 * compiler, which is the difference between an agent that was told the right
 * field names and one that cannot write the wrong ones. It matters most for
 * exactly the records the SDK cannot type on its own: a capability designed
 * last week on this machine is unknowable to a package published before it.
 *
 * Optionality is the part worth generating rather than writing by hand. A
 * capability marks a field required when every implementing site has it, and
 * that distinction is invisible in a sample record — the one hotel that
 * happened to show a price teaches you nothing about the site that never does.
 * Required becomes `name: T`, everything else `name?: T`, so the missing case
 * has to be handled where it is real.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import {
  CapabilityRegistry,
  canonicalCapability,
  type CapabilityDefinition,
} from "../capability/registry.js";
import { JOBS_CAPABILITY } from "../capability/jobs.js";
import type { FieldSpec } from "../shared/schema.js";
import type { PilotEnv } from "../shared/env.js";
import { flagString, type ParsedArgs } from "./args.js";

const DEFAULT_FILE = "pilot-types.d.ts";

/** Extraction always yields strings; `type` says how the runtime coerces. */
function tsType(field: FieldSpec): string {
  switch (field.type) {
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    default:
      return "string";
  }
}

/** `hotels.search@1` → `HotelsSearch1Record`. */
function interfaceName(id: string): string {
  const parts = id.split(/[.@-]/).filter(Boolean);
  return `${parts.map((part) => part[0]!.toUpperCase() + part.slice(1)).join("")}Record`;
}

function renderInterface(definition: CapabilityDefinition): string {
  const fields = definition.schema.fields
    .map((field) => {
      const optional = field.required ? "" : "?";
      return `  /** ${field.description.replace(/\*\//g, "*\\/")} */\n  ${field.name}${optional}: ${tsType(field)};`;
    })
    .join("\n");
  return (
    `/** ${definition.id} — schema ${definition.version}. */\n` +
    `export interface ${interfaceName(definition.id)} {\n${fields}\n}`
  );
}

export function runTypes(env: PilotEnv, args: ParsedArgs): number {
  const definitions = new CapabilityRegistry(env).all();
  if (definitions.length === 0) {
    process.stderr.write(
      "No capabilities installed, so there is nothing to generate.\n" +
        "  pilot install <capability>   take one someone published\n" +
        "  pilot create <capability>    declare your own\n",
    );
    return 1;
  }

  const interfaces = definitions.map(renderInterface).join("\n\n");

  // Both spellings are mapped, because both are things people type: the short
  // name is what the CLI and docs use, and the pinned one is what a project
  // writes when it wants to survive a future major.
  const entries = definitions
    // The jobs capability is excluded from the map: `capability("jobs.search")`
    // already matches the hand-written overload above it, which returns the
    // typed jobs client. Mapping it here would offer a worse type for the same
    // call. Its interface is still emitted, since it documents the contract.
    .filter((definition) => canonicalCapability(definition.id) !== JOBS_CAPABILITY)
    .flatMap((definition) => {
      const short = definition.id.split("@")[0]!;
      const name = interfaceName(definition.id);
      return [`  "${definition.id}": ${name};`, `  "${short}": ${name};`];
    })
    .join("\n");

  // The jobs capability already has a hand-written client with its own result
  // shape, so mapping it here would replace a better type with a worse one.
  const jobsNote = definitions.some(
    (definition) => canonicalCapability(definition.id) === JOBS_CAPABILITY,
  )
    ? `\n// ${JOBS_CAPABILITY} is deliberately absent: pilot().capability("jobs.search")\n` +
      `// already returns the typed jobs client, which knows more than this file could.\n`
    : "";

  const body =
    `// Generated by \`pilot types\`. Re-run it after installing or changing a\n` +
    `// capability. Checking it in is reasonable — it is a description of the\n` +
    `// interfaces this project is written against.\n\n` +
    `${interfaces}\n\n` +
    `declare module "pilot" {\n` +
    `  interface CapabilityTypes {\n${entries}\n  }\n` +
    `}\n${jobsNote}`;

  const file = path.resolve(env.projectRoot, flagString(args, "out") ?? DEFAULT_FILE);
  if (args.flags["dry-run"] === true) {
    process.stdout.write(body);
    return 0;
  }
  writeFileSync(file, body);
  process.stdout.write(
    `Wrote ${path.relative(env.projectRoot, file) || file}\n` +
      definitions.map((definition) => `  ${definition.id} → ${interfaceName(definition.id)}\n`).join("") +
      `\nInclude it in tsconfig, then capability("${definitions[0]!.id.split("@")[0]}") returns those fields.\n`,
  );
  return 0;
}
